# Generated by Django 4.1.7 on 2023-04-03 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_status_statusname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='endDate',
            new_name='completionDate',
        ),
    ]
