# Generated by Django 4.1.7 on 2023-04-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_rename_enddate_project_completiondate'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], default=True, max_length=100),
        ),
        migrations.AlterModelTable(
            name='status',
            table='status',
        ),
    ]
