# Generated by Django 4.1.7 on 2023-04-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_projectmodule_created_at_projectmodule_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodule',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], max_length=100),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], max_length=100),
        ),
    ]
